name: Auto Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    paths:
      - 'hw4/nextjs/**'
      - 'hw4/mitmproxy/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [nextjs, mitmproxy]

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Read version from Dockerfile
      run: |
        # 讀取 Dockerfile 中的 version
        file=hw4/${{ matrix.folder }}/Dockerfile
        version=$(grep -E '^(LABEL) +version *=*' "$file" | head -n1 | sed -E 's/.*[ =]+"?([0-9]+\.[0-9]+(\.[0-9]+)?)"?/\1/')
        if [ -z "$version" ]; then
          echo "::error::Failed to extract version from $file. Please add LABEL version=\"1.0\""
          exit 1
        fi
        echo "tag=${{ matrix.folder }}-$version"
        echo "tag=${{ matrix.folder }}-$version" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image with tag
      uses: docker/build-push-action@v5
      with:
        context: ./hw4/${{ matrix.folder }}
        push: true
        tags: tanimal19/2025cloud:${{ steps.version.outputs.tag }}
