name: Auto Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    paths:
      - "hw4/*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ["mitmproxy", "nextjs"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read version from Dockerfile
        id: version
        run: |
          file=hw4/${{ matrix.folder }}/Dockerfile
          version=$(grep -iE 'label +version *= *"?[0-9]+\.[0-9]+(\.[0-9]+)?"?' "$file" | sed -E 's/.*version *= *"?([0-9]+\.[0-9]+(\.[0-9]+)?)"?/\1/')
          echo "tag=${{ matrix.folder }}-$version"
          echo "tag=${{ matrix.folder }}-$version" >> $GITHUB_OUTPUT

      - name: Check if image tag exists on Docker Hub
        id: check-tag
        run: |
          IMAGE=tanimal19/2025cloud
          TAG=${{ steps.version.outputs.tag }}

          echo "Checking $IMAGE:$TAG..."

          response=$(curl -s -o /dev/null -w "%{http_code}" \
            https://hub.docker.com/v2/repositories/${IMAGE}/tags/${TAG}/)

          if [ "$response" -eq 200 ]; then
            echo "Image exists, skipping."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "Image does not exist."
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Log in to Docker Hub
        if: steps.check-tag.outputs.skip == 'false'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.check-tag.outputs.skip == 'false'
        uses: docker/build-push-action@v5
        with:
          context: ./hw4/${{ matrix.folder }}
          push: true
          tags: tanimal19/2025cloud:${{ steps.version.outputs.tag }}
