name: Auto Build with Tag from Dockerfile

on:
  push:
    paths:
      - "hw4/**"

jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [nextjs, mitmproxy]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Check if folder changed
        id: folder-check
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^hw4/${{ matrix.folder }}/" || true)
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

      - name: Read version from Dockerfile
        if: steps.folder-check.outputs.changed != ''
        id: version
        run: |
          file=hw4/${{ matrix.folder }}/Dockerfile
          # 讀取 Dockerfile 內的 version
          version=$(grep -E '^(LABEL) +version *=*' "$file" | head -n1 | sed -E 's/.*[ =]+"?([0-9]+\.[0-9]+(\.[0-9]+)?)"?/\1/')
          echo "tag=${{ matrix.folder }}-$version" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        if: steps.folder-check.outputs.changed != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image with tag
        if: steps.folder-check.outputs.changed != ''
        uses: docker/build-push-action@v5
        with:
          context: ./hw4/${{ matrix.folder }}
          push: true
          tags: |
            tanimal19/2025cloud:${{ steps.version.outputs.tag }}
