name: Auto Build and Push Docker Images

on:
  workflow_dispatch:
  push:
    paths:
      - "hw4/**"

jobs:
  detect-changed-folders:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.set-matrix.outputs.changed }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Get changed folders under hw4/
        id: set-matrix
        run: |
          changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^hw4/' | awk -F/ '{print $2}' | sort -u)
          folders=$(printf '%s\n' $changed | jq -R . | jq -s .)
          echo "Changed folders: $folders"
          echo "changed=$folders" >> $GITHUB_OUTPUT

  build-and-push:
    needs: detect-changed-folders
    runs-on: ubuntu-latest
    if: needs.detect-changed-folders.outputs.changed != '[]'
    strategy:
      matrix:
        folder: ${{ fromJson(needs.detect-changed-folders.outputs.changed) }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Read version from Dockerfile
        id: version
        run: |
          file=hw4/${{ matrix.folder }}/Dockerfile
          version=$(grep -iE 'label +version *= *"?[0-9]+\.[0-9]+(\.[0-9]+)?"?' "$file" | sed -E 's/.*version *= *"?([0-9]+\.[0-9]+(\.[0-9]+)?)"?/\1/')
          if [ -z "$version" ]; then
            echo "::error::Missing or invalid LABEL version in $file"
            exit 1
          fi
          echo "tag=${{ matrix.folder }}-$version" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./hw4/${{ matrix.folder }}
          push: true
          tags: tanimal19/2025cloud:${{ steps.version.outputs.tag }}
